/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_secure_SecureHasher */

#ifndef _Included_com_secure_SecureHasher
#define _Included_com_secure_SecureHasher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_secure_SecureHasher
 * Method:    hashAndEncrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_secure_SecureHasher_hashAndEncrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
